# Generated by Django 5.2.14 on 2026-06-14 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.TextField(blank=True)),
                ('avatar_url', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='jobs.company')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'email')},
            },
        ),
        migrations.CreateModel(
            name='RecruiterOutreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('initial', 'Initial'), ('follow_up', 'Follow Up'), ('thank_you', 'Thank You'), ('networking', 'Networking')], db_index=True, default='initial', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('opened', 'Opened'), ('replied', 'Replied'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreaches', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='accounts.organization')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='recruiters.recruiter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
