# Generated by Django 5.2.14 on 2026-06-14 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('target_titles', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('target_companies', models.JSONField(blank=True, default=list)),
                ('target_industries', models.JSONField(blank=True, default=list)),
                ('target_salary_min', models.IntegerField(blank=True, null=True)),
                ('target_salary_max', models.IntegerField(blank=True, null=True)),
                ('target_remote', models.BooleanField(blank=True, null=True)),
                ('target_seniority', models.JSONField(blank=True, default=list)),
                ('target_skills', models.JSONField(blank=True, default=list)),
                ('exclude_titles', models.JSONField(blank=True, default=list)),
                ('exclude_companies', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('auto_apply', models.BooleanField(default=False)),
                ('require_approval', models.BooleanField(default=True)),
                ('max_applications_per_day', models.IntegerField(default=20)),
                ('min_fit_score', models.IntegerField(default=70)),
                ('application_window_start', models.TimeField(blank=True, null=True)),
                ('application_window_end', models.TimeField(blank=True, null=True)),
                ('schedule_frequency', models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('continuous', 'Continuous')], default='one_time', max_length=20)),
                ('schedule_start', models.DateTimeField(blank=True, null=True)),
                ('schedule_end', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_found', models.IntegerField(default=0)),
                ('jobs_analyzed', models.IntegerField(default=0)),
                ('applications_submitted', models.IntegerField(default=0)),
                ('interviews_booked', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.organization')),
                ('resume_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
