# Generated by Django 5.2.14 on 2026-06-14 06:45

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0002_enable_pgvector'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('profile_slug', models.SlugField(max_length=100)),
                ('parsed_text', models.TextField(blank=True)),
                ('parsed_html', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('target_industries', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('target_salary_min', models.IntegerField(blank=True, null=True)),
                ('target_salary_max', models.IntegerField(blank=True, null=True)),
                ('preferred_remote', models.BooleanField(blank=True, null=True)),
                ('open_to_relocation', models.BooleanField(blank=True, null=True)),
                ('work_authorization', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=50)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='common.fileupload')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
                'unique_together': {('organization', 'profile_slug')},
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.IntegerField()),
                ('original_text', models.TextField(blank=True)),
                ('optimized_text', models.TextField(blank=True)),
                ('changes_summary', models.JSONField(blank=True, default=dict)),
                ('ats_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.fileupload')),
                ('optimized_for_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('resume', 'version_number')},
            },
        ),
    ]
