# Generated by Django 5.2.14 on 2026-06-14 06:45

import apps.common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('storage_path', models.TextField()),
                ('storage_bucket', models.CharField(blank=True, max_length=255)),
                ('storage_provider', models.CharField(default='local', max_length=50)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('is_public', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='accounts.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_timezone', models.CharField(default='UTC', max_length=50)),
                ('default_locale', models.CharField(default='en', max_length=10)),
                ('default_min_fit_score', models.IntegerField(default=70)),
                ('max_applications_per_day', models.IntegerField(default=20)),
                ('default_cover_letter_style', models.CharField(default='medium', max_length=20)),
                ('require_approval', models.BooleanField(default=True)),
                ('application_window_start', models.TimeField(blank=True, null=True)),
                ('application_window_end', models.TimeField(blank=True, null=True)),
                ('auto_optimize_resume', models.BooleanField(default=False)),
                ('stealth_mode', models.BooleanField(default=True)),
                ('proxy_enabled', models.BooleanField(default=False)),
                ('proxy_config', models.JSONField(blank=True, default=dict)),
                ('browser_fingerprint_rotation', models.BooleanField(default=True)),
                ('human_like_delays', models.BooleanField(default=True)),
                ('retry_on_failure', models.BooleanField(default=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('captcha_handling', models.CharField(default='manual', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('slack_webhook_url', models.TextField(blank=True)),
                ('discord_webhook_url', models.TextField(blank=True)),
                ('linkedin_username', models.TextField(blank=True)),
                ('linkedin_password', apps.common.fields.EncryptedTextField(blank=True)),
                ('indeed_username', models.TextField(blank=True)),
                ('indeed_password', apps.common.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'organization settings',
            },
        ),
    ]
