# Generated by Django 5.2.14 on 2026-06-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_enable_pgvector'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='default_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resume'),
        ),
    ]
