# Generated by Django 5.2.14 on 2026-05-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachemail',
            name='dispatch_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='dispatch_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='outreach_screenshots/'),
        ),
    ]
