# Generated by Django 5.2.14 on 2026-06-14 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screen'), ('video', 'Video Call'), ('onsite', 'On-Site'), ('technical', 'Technical'), ('final', 'Final Round'), ('take_home', 'Take Home'), ('group', 'Group Interview')], db_index=True, max_length=50)),
                ('round', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('interviewers', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_action', models.TextField(blank=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.organization')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'unique_together': {('application', 'round')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='negotiating', max_length=20)),
                ('base_salary', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('equity', models.CharField(blank=True, max_length=100)),
                ('signing_bonus', models.IntegerField(blank=True, null=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('relocation_package', models.TextField(blank=True)),
                ('offer_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('counter_offer_amount', models.IntegerField(blank=True, null=True)),
                ('counter_offer_details', models.TextField(blank=True)),
                ('negotiation_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.organization')),
            ],
            options={
                'ordering': ['-offer_date'],
                'unique_together': {('application', 'organization')},
            },
        ),
    ]
