# Generated by Django 5.2.14 on 2026-06-14 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('style', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('custom', 'Custom')], db_index=True, default='medium', max_length=20)),
                ('tone', models.CharField(default='professional', max_length=50)),
                ('length', models.IntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('salutation', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('closing', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('model_used', models.CharField(default='gpt-4o', max_length=100)),
                ('prompt_template', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='accounts.organization')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
