# Generated by Django 5.2.14 on 2026-06-14 11:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_limit_cents', models.IntegerField(default=5000)),
                ('weekly_limit_cents', models.IntegerField(default=35000)),
                ('monthly_limit_cents', models.IntegerField(default=150000)),
                ('soft_limit_pct', models.FloatField(default=80.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('alert_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_budgets', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'AI budgets',
                'db_table': 'ai_budgets',
            },
        ),
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_titles', models.JSONField(blank=True, default=list)),
                ('target_salary_min', models.IntegerField(blank=True, null=True)),
                ('target_salary_max', models.IntegerField(blank=True, null=True)),
                ('target_companies', models.JSONField(blank=True, default=list)),
                ('target_industries', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('remote_preference', models.CharField(choices=[('remote', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('any', 'Any')], default='any', max_length=20)),
                ('open_to_relocation', models.BooleanField(default=False)),
                ('visa_sponsorship_needed', models.BooleanField(default=False)),
                ('work_authorization', models.CharField(blank=True, max_length=50, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=30, null=True)),
                ('employment_type', models.CharField(default='full_time', max_length=30)),
                ('min_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('excluded_skills', models.JSONField(blank=True, default=list)),
                ('excluded_companies', models.JSONField(blank=True, default=list)),
                ('excluded_titles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('task_type', models.CharField(db_index=True, max_length=100)),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField(blank=True, null=True)),
                ('response_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for structured output validation')),
                ('temperature', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(default=4096)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_prompt_templates',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['task_type', 'is_active'], name='ai_prompt_t_task_ty_e2f80d_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(db_index=True, max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('fallback', 'Fallback')], db_index=True, default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('prompt_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'task_type'], name='ai_requests_organiz_86b46f_idx'), models.Index(fields=['organization', 'created_at'], name='ai_requests_organiz_ae46f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareerMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('success_pattern', 'Success Pattern'), ('failure_pattern', 'Failure Pattern'), ('insight', 'Insight'), ('preference', 'Preference'), ('feedback', 'Feedback'), ('observation', 'Observation')], db_index=True, max_length=50)),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('value', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_memories', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_memories',
                'ordering': ['-confidence'],
                'indexes': [models.Index(fields=['user', 'memory_type'], name='career_memo_user_id_91d2fd_idx')],
                'unique_together': {('user', 'memory_type', 'key')},
            },
        ),
    ]
