# Generated by Django 5.2.14 on 2026-06-14 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('keyword_match_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('formatting_score', models.IntegerField(default=0)),
                ('section_score', models.IntegerField(default=0)),
                ('missing_sections', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('suggested_improvements', models.JSONField(blank=True, default=list)),
                ('optimized_sections', models.JSONField(blank=True, default=dict)),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='resumes.resume')),
            ],
            options={
                'verbose_name_plural': 'ats analyses',
                'unique_together': {('job', 'resume')},
            },
        ),
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('years_experience_required', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=50)),
                ('education_required', models.CharField(blank=True, max_length=255)),
                ('certifications_required', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('salary_range', models.JSONField(blank=True, default=dict)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('fit_score', models.IntegerField(default=0)),
                ('ats_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('skill_match_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('location_score', models.IntegerField(default=0)),
                ('salary_score', models.IntegerField(default=0)),
                ('education_score', models.IntegerField(default=0)),
                ('seniority_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('experience_gaps', models.JSONField(blank=True, default=list)),
                ('keyword_gaps', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('recommendation', models.CharField(choices=[('strong_apply', 'Strong Apply'), ('apply', 'Apply'), ('consider', 'Consider'), ('skip', 'Skip')], db_index=True, default='consider', max_length=20)),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(default='gpt-4o', max_length=100)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='jobs.job')),
                ('resume_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resume')),
            ],
            options={
                'verbose_name_plural': 'job analyses',
                'unique_together': {('job', 'resume_profile')},
            },
        ),
    ]
