# Generated by Django 5.2.14 on 2026-05-21 22:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('google_description', models.TextField(blank=True, null=True)),
                ('has_website', models.BooleanField(default=False)),
                ('has_booking_system', models.BooleanField(default=False)),
                ('digital_score', models.IntegerField(default=0)),
                ('analysis_notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
