# Generated by Django 5.2.14 on 2026-05-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auto_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
